apiVersion: v1
data:
    password: ENC[AES256_GCM,data:7//ne8sZWTw=,iv:qYC6JOGVA6h5SadvH0OEcLmNAw5UPXV9mzuXU+YckN4=,tag:1+KBufMlkAHArnuavoJI4Q==,type:str]
    user: ENC[AES256_GCM,data:gFM/jr6JNEg=,iv:P3Vx1eX+X939jM2FU7whQoZ0ELbHfmOjlzxki7rAxdQ=,tag:Ha1e6tHSYkNzBH9BkJb7cg==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1c3ze55g8n2zmuv3qzxqtu2vjvlgjcw4h74lhquu4xydnz80fddmstxkklr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bXljZXBrMVIwYWlNZDE2
            SnJ2RDZacHQzMWhtL2lkT3BzZk1ZOW5DRmdrClQ2aDJSVUlzOTVQUjdKU29hWk9Z
            NDF1MDczaWNtYkx0dDhLVUh0OE9YWVUKLS0tIFRCc0hEYktYM3k5OG04RDdsK0tY
            T1JUN1hLUGViRXdqOXUxMUQ5QjdlVTgKEgtbjnHsxOAAokRZvy2f+/MdLaxtfbrM
            WNgi1xSKb7zQDGfHLCmG7wrn7NZSDxbmeDFSVfMyMcBFtIWr91K5sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T23:13:27Z"
    mac: ENC[AES256_GCM,data:LPG9pu54dF0DIemsHMCryWqG4YCiL1nyTE7PylDBUiJs3doJwErxrREgP94j4lh7Cy3pu2eSjnn0aSkWk41Um+Bzs3fF+FEW1/yOc9RFyDHKCW6r1KNeiFC8eka+tDhoJVK+dGgsxluy7vqwdZ3oYLwUZxFBUn4VByo6dxtpHWY=,iv:Afs76sDCn4hGQ0TCWAUdvoJtn80vulvRXRbN4Ffohi8=,tag:pPBa1TBWIA+RKzc62WjV8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
